const $=s=>document.querySelector(s);
const courts=[{name:'Quadra 01',sport:'Vôlei',price:100},{name:'Quadra 02',sport:'Beach tennis',price:120},{name:'Quadra 03',sport:'Futsal',price:150}];
const hours=Array.from({length:9},(_,i)=>i+14);
const localDate=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const today=localDate(new Date());let day=today,view='admin',filter='all',selectedId=null,counter=20;
const bookings=[{id:1,court:0,hour:14,name:'Marina Costa',status:'confirmed',paid:true},{id:2,court:1,hour:15,name:'Bruno Almeida',status:'confirmed',paid:true},{id:3,court:2,hour:16,name:'Equipe Resenha',status:'confirmed',paid:false},{id:4,court:0,hour:17,name:'Turma do vôlei',status:'confirmed',paid:true},{id:5,court:1,hour:18,name:'Camila Santos',status:'pending',paid:false},{id:6,court:0,hour:19,name:'Julian Matheus',status:'pending',paid:false},{id:7,court:2,hour:20,name:'Amigos da bola',status:'confirmed',paid:true}].map(b=>({...b,date:today}));
const money=v=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labelDate=d=>new Date(d+'T12:00:00').toLocaleDateString('pt-BR',{day:'numeric',month:'long'});
const getBooking=(court,hour)=>bookings.find(b=>b.date===day&&b.court===court&&b.hour===hour);
function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',4200)}
function setView(v){view=v;render()}
function render(){
 $('#date').value=day;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
 const admin=view==='admin';$('#crumb').textContent=admin?'Agenda e reservas':'Visão do jogador';$('#eyebrow').textContent=admin?'CONTROLE DA ARENA':'ARENA VILA · PORTO VELHO';$('#title').textContent=admin?'Bom jogo começa com uma boa agenda.':'Seu próximo jogo começa aqui.';$('#subtitle').textContent=admin?'Todos os horários. Cada reserva. Tudo no seu lugar.':'Escolha a quadra, encontre seu horário e solicite uma reserva.';$('#newBooking').textContent=admin?'＋ Nova reserva':'＋ Solicitar reserva';$('#workspaceTitle').textContent=admin?'Agenda de quadras':'Encontre seu horário';$('#workspaceSubtitle').textContent=admin?'Selecione um horário para reservar ou ver os detalhes.':'Cada reserva dura 1 hora. Aguarde a confirmação da arena.';
 const list=bookings.filter(b=>b.date===day);const confirmed=list.filter(b=>b.status==='confirmed');const pending=list.filter(b=>b.status==='pending');
 $('#stats').innerHTML=(admin?[['Reservas do dia',list.length,'Confirmadas e aguardando','▦'],['Ocupação',Math.round(confirmed.length/27*100)+'%','Dos 27 horários disponíveis','◷'],['Recebido',money(list.filter(b=>b.paid).reduce((n,b)=>n+courts[b.court].price,0)),'Pagamentos registrados','↗'],['A confirmar',pending.length,'Solicitações aguardando você','◌']]:[['Quadras',3,'Três espaços para jogar','▦'],['Duração','1 hora','Por reserva','◷'],['A partir de',money(100),'Por quadra / hora','↗'],['Horários livres',27-list.length,'Na data selecionada','◌']]).map((s,i)=>`<div class="stat ${i===2?'featured':''}"><div class="stat-label">${s[0]}<span class="stat-symbol" aria-hidden="true">${s[3]}</span></div><strong>${s[1]}</strong><small>${s[2]}</small></div>`).join('');
 const cols=courts.map((c,i)=>({...c,i})).filter(c=>filter==='all'||String(c.i)===filter);
 $('#schedule').style.setProperty('--cols',cols.length);
 $('#schedule').innerHTML=`<div class="grid-head"><span></span>${cols.map(c=>`<div class="court-head"><strong>${c.name}</strong><small>${c.sport} · ${money(c.price)}/h</small></div>`).join('')}</div>`+hours.map(h=>`<div class="time-row"><div class="hour">${h}:00</div>${cols.map(c=>{const b=getBooking(c.i,h);return `<button class="slot ${b?(b.status==='pending'?'waiting':'booked'):''} ${b&&!admin?'blocked':''}" data-court="${c.i}" data-hour="${h}" ${b&&!admin?'disabled':''} aria-label="${esc(c.name+' às '+h+' horas, '+(b?'ocupado':'disponível'))}"><strong>${b?(admin?esc(b.name):'Indisponível'):'+ Reservar'}</strong><small>${b?(admin?(b.status==='pending'?'A confirmar':b.paid?'Confirmada · Pago':'Confirmada · A pagar'):'Horário ocupado'):'Disponível'}</small></button>`}).join('')}</div>`).join('');
 $('#dateCaption').textContent=labelDate(day);$('#bottom').hidden=!admin;$('#bottom').style.display=admin?'grid':'none';$('#pendingCount').textContent=pending.length;
 $('#requests').innerHTML=pending.length?pending.map(b=>`<div class="request-row"><span class="avatar">${esc(b.name.split(' ').map(s=>s[0]).slice(0,2).join(''))}</span><div><strong>${esc(b.name)}</strong><small>${courts[b.court].name} · ${b.hour}:00–${b.hour+1}:00 · ${money(courts[b.court].price)}</small></div><button data-detail="${b.id}">Ver solicitação</button></div>`).join(''):'<div class="empty">Tudo em dia. Nenhuma solicitação pendente nesta data.</div>';
}
function updateHours(preferred){const c=Number($('#bookingCourt').value);const free=hours.filter(h=>!getBooking(c,h));$('#bookingHour').innerHTML=free.length?free.map(h=>`<option value="${h}">${h}:00 – ${h+1}:00</option>`).join(''):'<option value="">Sem horários livres</option>';if(free.includes(preferred))$('#bookingHour').value=String(preferred);$('#price').textContent=money(courts[c].price);$('#submitBooking').disabled=!free.length}
function openBooking(c=0,h){selectedId=null;$('#bookingForm').reset();$('#formError').textContent='';$('#formFields').hidden=false;$('#detailContent').innerHTML='';$('#dialogTitle').textContent=view==='admin'?'Nova reserva':'Solicitar reserva';$('#dialogInfo').textContent=labelDate(day)+' · Arena Vila';$('#bookingCourt').value=String(c);$('#dialogActions').innerHTML=`<button class="primary" type="submit" id="submitBooking">${view==='admin'?'Confirmar reserva':'Solicitar horário'}</button>`;updateHours(h);$('#bookingDialog').showModal()}
function openDetail(id){const b=bookings.find(b=>b.id===id);if(!b||view!=='admin')return;selectedId=id;$('#formError').textContent='';$('#formFields').hidden=true;$('#dialogTitle').textContent=b.status==='pending'?'Solicitação de reserva':'Detalhes da reserva';$('#dialogInfo').textContent=`${labelDate(b.date)} · ${b.hour}:00–${b.hour+1}:00`;$('#detailContent').innerHTML=`<p><strong>${esc(b.name)}</strong></p><p>${courts[b.court].name} · ${courts[b.court].sport}</p><p>Status: ${b.status==='pending'?'Aguardando confirmação':'Confirmada'}<br>Pagamento: ${b.paid?'Recebido':'Pendente'}</p>`;$('#price').textContent=money(courts[b.court].price);$('#dialogActions').innerHTML=(b.status==='pending'?'<button type="button" class="primary" data-action="confirm">Confirmar reserva</button>':!b.paid?'<button type="button" class="primary" data-action="pay">Registrar pagamento</button>':'')+'<button type="button" class="secondary danger" data-action="cancel">Cancelar reserva</button>';if(!$('#bookingDialog').open)$('#bookingDialog').showModal()}
$('#bookingForm').addEventListener('submit',e=>{e.preventDefault();if(selectedId!==null)return;const c=Number($('#bookingCourt').value),raw=$('#bookingHour').value,h=Number(raw),name=$('#customer').value.trim();if(!name){$('#formError').textContent='Informe o nome do responsável.';return}if(raw===''||!hours.includes(h)||!courts[c]||getBooking(c,h)){$('#formError').textContent='Este horário não está disponível. Escolha outro.';return}bookings.push({id:++counter,date:day,court:c,hour:h,name,status:view==='admin'?'confirmed':'pending',paid:false});$('#bookingDialog').close();render();toast(view==='admin'?'Reserva confirmada na demonstração.':'Solicitação enviada! Veja a confirmação na visão de gestão.');});
$('#dialogActions').addEventListener('click',e=>{const action=e.target.dataset.action,b=bookings.find(b=>b.id===selectedId);if(!action||!b)return;if(action==='confirm'){b.status='confirmed';toast('Reserva confirmada.')}if(action==='pay'){b.paid=true;toast('Pagamento registrado na demonstração.')}if(action==='cancel'){if(!confirm('Cancelar esta reserva de demonstração e liberar o horário?'))return;bookings.splice(bookings.indexOf(b),1);toast('Reserva cancelada. Horário disponível novamente.')}$('#bookingDialog').close();render()});
$('#bookingCourt').addEventListener('change',()=>updateHours());$('#closeDialog').onclick=()=>$('#bookingDialog').close();$('#newBooking').onclick=()=>openBooking(filter==='all'?0:Number(filter));$('#seePlayer').onclick=()=>{setView('player');window.scrollTo({top:0,behavior:'smooth'})};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#schedule').addEventListener('click',e=>{const btn=e.target.closest('[data-court]');if(!btn)return;const c=Number(btn.dataset.court),h=Number(btn.dataset.hour),b=getBooking(c,h);b?openDetail(b.id):openBooking(c,h)});$('#requests').addEventListener('click',e=>{const b=e.target.closest('[data-detail]');if(b)openDetail(Number(b.dataset.detail))});$('#courtFilter').onchange=e=>{filter=e.target.value;render()};$('#date').onchange=e=>{if(e.target.value){day=e.target.value;render()}};function moveDay(n){const d=new Date(day+'T12:00:00');d.setDate(d.getDate()+n);day=localDate(d);render()}$('#prevDay').onclick=()=>moveDay(-1);$('#nextDay').onclick=()=>moveDay(1);$('#today').onclick=()=>{day=today;render()};render();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'change_booking_view',title:'Alterar visão da agenda',description:'Abre a visão do administrador ou do jogador no protótipo, sem criar reservas.',inputSchema:{type:'object',properties:{view:{type:'string',enum:['admin','player']}},required:['view'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||!['admin','player'].includes(input.view))throw new Error('Visão inválida');setView(input.view);return{view,title:$('#title').textContent}}})).catch(()=>{})}catch{}}
