-- Audit metadata is generated by the database, never by the browser.
-- Existing records are preserved; historical authorship cannot be reconstructed.
create or replace function private.stamp_cash_expense_creation()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if auth.uid() is null then
    raise exception 'Autenticação obrigatória para registrar despesas.' using errcode = '42501';
  end if;
  new.created_by := auth.uid();
  new.created_at := statement_timestamp();
  new.updated_at := new.created_at;
  return new;
end;
$$;

revoke all on function private.stamp_cash_expense_creation() from public, anon, authenticated;
drop trigger if exists cash_expenses_stamp_creation on public.cash_expenses;
create trigger cash_expenses_stamp_creation
before insert on public.cash_expenses
for each row execute function private.stamp_cash_expense_creation();

-- Remove table-wide and any existing column-level UPDATE permissions.
revoke update on public.cash_expenses from public, anon, authenticated;
revoke update (id, arena_id, expense_date, description, category, payment_method,
  amount, created_by, created_at, updated_at)
on public.cash_expenses from public, anon, authenticated;
grant update (expense_date, description, category, payment_method, amount)
on public.cash_expenses to authenticated;

-- Client roles must not be able to install triggers or truncate the ledger.
revoke truncate, references, trigger on public.cash_expenses from public, anon, authenticated;
